import React from 'react';

/**
 * TextSummary Component
 * Displays the structured meeting summary generated by Gemini
 */
function TextSummary({ summary, onDownload }) {
  if (!summary) {
    return (
      <div className="card text-summary fade-in">
        <div className="card-header">
          <h2 className="card-title">
            <span className="card-title-icon">📋</span>
            Meeting Summary
          </h2>
        </div>
        <div className="card-body">
          <p style={{ color: 'var(--text-muted)' }}>No summary data available</p>
        </div>
      </div>
    );
  }

  return (
    <div className="card text-summary fade-in">
      <div className="card-header">
        <h2 className="card-title">
          <span className="card-title-icon">📋</span>
          Meeting Summary
        </h2>
        <button className="btn btn-secondary btn-icon" onClick={onDownload} title="Download Summary">
          ⬇️
        </button>
      </div>
      
      <div className="card-body">
        {/* Key Points */}
        {summary.summary && summary.summary.length > 0 && (
          <div className="summary-section">
            <h3 className="section-title">Key Points</h3>
            <ul className="summary-list">
              {summary.summary.map((point, index) => (
                <li key={index}>
                  <span className="list-bullet"></span>
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Decisions Made */}
        {summary.decisions && summary.decisions.length > 0 && (
          <div className="summary-section">
            <h3 className="section-title">Decisions Made</h3>
            <ul className="summary-list decisions-list">
              {summary.decisions.map((decision, index) => (
                <li key={index}>
                  <span className="list-bullet"></span>
                  <span>{decision}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Action Items */}
        {summary.actionItems && summary.actionItems.length > 0 && (
          <div className="summary-section">
            <h3 className="section-title">Action Items</h3>
            <div className="action-items">
              {summary.actionItems.map((item, index) => (
                <div key={index} className="action-item">
                  <div className="action-task">{item.task}</div>
                  <div className="action-meta">
                    <span>
                      <span>👤</span>
                      {item.owner || 'Unassigned'}
                    </span>
                    <span>
                      <span>📅</span>
                      {item.deadline || 'TBD'}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Key Topics */}
        {summary.keyTopics && summary.keyTopics.length > 0 && (
          <div className="summary-section">
            <h3 className="section-title">Key Topics</h3>
            <div className="topics-list">
              {summary.keyTopics.map((topic, index) => (
                <span key={index} className="topic-tag">{topic}</span>
              ))}
            </div>
          </div>
        )}

        {/* Participants */}
        {summary.participants && summary.participants.length > 0 && (
          <div className="summary-section">
            <h3 className="section-title">Participants</h3>
            <div className="topics-list">
              {summary.participants.map((person, index) => (
                <span key={index} className="topic-tag" style={{ 
                  background: 'rgba(59, 130, 246, 0.1)',
                  borderColor: 'rgba(59, 130, 246, 0.2)',
                  color: '#60a5fa'
                }}>
                  👤 {person}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Meeting Info */}
        <div className="summary-section">
          <h3 className="section-title">Meeting Info</h3>
          <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
            {summary.mood && (
              <div className={`mood-indicator ${summary.mood}`}>
                <span>{getMoodEmoji(summary.mood)}</span>
                <span>{capitalizeFirst(summary.mood)}</span>
              </div>
            )}
            {summary.duration_estimate && (
              <div className="mood-indicator" style={{
                background: 'rgba(156, 163, 175, 0.1)',
                borderColor: 'rgba(156, 163, 175, 0.2)',
                color: '#9ca3af'
              }}>
                <span>⏱️</span>
                <span>{summary.duration_estimate}</span>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * Get emoji for meeting mood
 */
function getMoodEmoji(mood) {
  const emojis = {
    productive: '🚀',
    creative: '💡',
    tense: '😬',
    informational: 'ℹ️',
    collaborative: '🤝'
  };
  return emojis[mood] || '📊';
}

/**
 * Capitalize first letter
 */
function capitalizeFirst(str) {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export default TextSummary;
