import React, { useState, useRef, useEffect } from 'react';

/**
 * VideoPlayer Component
 * Displays the Veo 3 generated video summary
 */
function VideoPlayer({ videoUrl, videoScript, hasVideo, videoError }) {
  const videoRef = useRef(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [showScript, setShowScript] = useState(false);
  const [videoLoaded, setVideoLoaded] = useState(false);
  const [loadError, setLoadError] = useState(null);

  useEffect(() => {
    if (videoRef.current) {
      videoRef.current.addEventListener('play', () => setIsPlaying(true));
      videoRef.current.addEventListener('pause', () => setIsPlaying(false));
      videoRef.current.addEventListener('ended', () => setIsPlaying(false));
      videoRef.current.addEventListener('loadeddata', () => setVideoLoaded(true));
      videoRef.current.addEventListener('error', (e) => {
        setLoadError('Failed to load video');
        console.error('Video load error:', e);
      });
    }
  }, [videoUrl]);

  const handlePlayPause = () => {
    if (videoRef.current) {
      if (isPlaying) {
        videoRef.current.pause();
      } else {
        videoRef.current.play();
      }
    }
  };

  const handleDownload = () => {
    if (videoUrl) {
      const a = document.createElement('a');
      a.href = videoUrl;
      a.download = `meeting-summary-video-${new Date().toISOString().split('T')[0]}.mp4`;
      a.click();
    }
  };

  const handleFullscreen = () => {
    if (videoRef.current) {
      if (videoRef.current.requestFullscreen) {
        videoRef.current.requestFullscreen();
      } else if (videoRef.current.webkitRequestFullscreen) {
        videoRef.current.webkitRequestFullscreen();
      }
    }
  };

  // Get style display name
  const getStyleDisplayName = (style) => {
    const names = {
      animated_diagram: 'Animated Diagram',
      whiteboard: 'Whiteboard Style',
      presenter: 'Presenter',
      story: 'Story Narrative'
    };
    return names[style] || 'AI Generated';
  };

  // No video available
  if (!hasVideo || videoError) {
    return (
      <div className="card video-section fade-in">
        <div className="card-header">
          <h2 className="card-title">
            <span className="card-title-icon">🎬</span>
            Video Summary
          </h2>
        </div>
        <div className="card-body">
          <div className="video-container">
            <div className="video-placeholder">
              <div className="video-placeholder-icon">
                {videoError ? '⚠️' : '🎥'}
              </div>
              <p className="video-placeholder-text">
                {videoError || 'Video summary not available'}
              </p>
            </div>
          </div>
          
          {/* Still show video script if available */}
          {videoScript && (
            <div className="video-script-preview">
              <button 
                className="btn btn-secondary"
                onClick={() => setShowScript(!showScript)}
                style={{ width: '100%', marginBottom: '12px' }}
              >
                {showScript ? '▲ Hide' : '▼ Show'} Video Script (Generated by Gemini)
              </button>
              
              {showScript && (
                <VideoScriptPreview videoScript={videoScript} />
              )}
            </div>
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="card video-section slide-up">
      <div className="card-header">
        <h2 className="card-title">
          <span className="card-title-icon">🎬</span>
          Video Summary
        </h2>
        <div className="badge veo">
          <span>Generated by Veo 3</span>
        </div>
      </div>
      
      <div className="card-body">
        {/* Video Container */}
        <div className="video-container">
          {!videoLoaded && !loadError && (
            <div className="video-placeholder">
              <div className="video-placeholder-icon" style={{ animation: 'pulse 2s infinite' }}>
                ⏳
              </div>
              <p className="video-placeholder-text">Loading video...</p>
            </div>
          )}
          
          {loadError && (
            <div className="video-placeholder">
              <div className="video-placeholder-icon">⚠️</div>
              <p className="video-placeholder-text">{loadError}</p>
            </div>
          )}
          
          <video 
            ref={videoRef}
            className="video-player"
            src={videoUrl}
            poster=""
            style={{ display: videoLoaded && !loadError ? 'block' : 'none' }}
            onClick={handlePlayPause}
          />
        </div>

        {/* Video Controls */}
        <div className="video-controls">
          <div className="video-info">
            <span className="video-style">
              {videoScript?.selectedStyle ? getStyleDisplayName(videoScript.selectedStyle) : 'AI Generated'}
            </span>
            <span className="video-duration">
              {videoScript?.videoDurationSeconds ? `${videoScript.videoDurationSeconds}s` : 'Video Summary'}
            </span>
          </div>
          
          <div className="video-actions">
            <button 
              className="btn btn-primary" 
              onClick={handlePlayPause}
              disabled={!videoLoaded}
            >
              {isPlaying ? '⏸️ Pause' : '▶️ Play'}
            </button>
            <button 
              className="btn btn-secondary btn-icon" 
              onClick={handleFullscreen}
              title="Fullscreen"
              disabled={!videoLoaded}
            >
              ⛶
            </button>
            <button 
              className="btn btn-secondary btn-icon" 
              onClick={handleDownload}
              title="Download Video"
            >
              ⬇️
            </button>
          </div>
        </div>

        {/* Video Script Preview */}
        {videoScript && (
          <div className="video-script-preview">
            <button 
              className="btn btn-secondary"
              onClick={() => setShowScript(!showScript)}
              style={{ width: '100%', marginBottom: '12px' }}
            >
              {showScript ? '▲ Hide' : '▼ Show'} Video Script
            </button>
            
            {showScript && (
              <VideoScriptPreview videoScript={videoScript} />
            )}
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Video Script Preview Component
 */
function VideoScriptPreview({ videoScript }) {
  return (
    <div className="fade-in">
      {/* Style reasoning */}
      {videoScript.reasoning && (
        <div style={{ 
          marginBottom: '16px', 
          padding: '12px',
          background: 'rgba(139, 92, 246, 0.1)',
          borderRadius: '10px',
          fontSize: '13px',
          color: 'var(--text-secondary)'
        }}>
          <strong style={{ color: '#a78bfa' }}>Why this style?</strong>
          <br />
          {videoScript.reasoning}
        </div>
      )}

      {/* Scene breakdown */}
      <h4 className="script-title">Scene Breakdown</h4>
      {videoScript.scenes?.map((scene, index) => (
        <div key={index} className="script-scene">
          <div className="scene-header">
            <span className="scene-number">Scene {scene.sceneNumber}</span>
            <span className="scene-duration">{scene.duration}s</span>
          </div>
          <p className="scene-narration">"{scene.narration}"</p>
          {scene.keyInsight && (
            <div style={{ 
              marginTop: '8px',
              fontSize: '12px',
              color: 'var(--accent-purple)'
            }}>
              💡 {scene.keyInsight}
            </div>
          )}
        </div>
      ))}

      {/* Veo Prompt (for debugging/interest) */}
      {videoScript.veoPrompt && (
        <div style={{ marginTop: '16px' }}>
          <h4 className="script-title">Veo 3 Prompt</h4>
          <div style={{
            padding: '12px',
            background: 'var(--bg-elevated)',
            borderRadius: '10px',
            fontSize: '12px',
            color: 'var(--text-muted)',
            fontFamily: "'JetBrains Mono', monospace",
            lineHeight: '1.6',
            maxHeight: '150px',
            overflow: 'auto'
          }}>
            {videoScript.veoPrompt}
          </div>
        </div>
      )}
    </div>
  );
}

export default VideoPlayer;
